//* This file is part of the MOOSE framework
//* https://www.mooseframework.org
//*
//* All rights reserved, see COPYRIGHT for full restrictions
//* https://github.com/idaholab/moose/blob/master/COPYRIGHT
//*
//* Licensed under LGPL 2.1, please see LICENSE for details
//* https://www.gnu.org/licenses/lgpl-2.1.html

#pragma once

#include "MeshGenerator.h"

/**
 * Allows multiple mesh files to be "stitched" together to form a single mesh.
 */
class TestExtrudedConcentricCircleMeshGenerator : public MeshGenerator
{
public:
  static InputParameters validParams();

  TestExtrudedConcentricCircleMeshGenerator(const InputParameters & parameters);

  std::unique_ptr<MeshBase> generate() override;

protected:
  /// The extruded mesh that is generated by a subgenerator; we need this so that
  /// once _this_ generator is called, we can simply pass off the resulting mesh
  /// from the extruder
  std::unique_ptr<MeshBase> * _extruded_mesh;
};
